### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by marthoc** [marthoc/docker-deconz#1]
- [x] Add docker-compose file
- [x] Refactor Dockerfile for better build caching
- [x] Create OTAU directory via Dockerfile
- [x] Change instructions to prefer net=host
- [x] Add armhf support
- [x] Add TravisCI build pipeline
- [x] Add RaspBee support
- [x] Investigate firmware update support

**Comment by Kane610** [comment]
Add a docker-compose file to that list 👍

**Comment by marthoc** [comment]
docker-compose.yml done... will be in the repo in the next push I do which will be shortly.

**Comment by marthoc** [comment]
Repo updated - made some changes to the way the container runs, added additional variables, better documentation in README.md.

@Kane610 - docker-compose.yml in the repo now!
